Visual Studio Code (1.97.2, ssh-remote, desktop)
Jupyter Extension Version: 2025.1.0.
Python Extension Version: 2025.0.0.
Pylance Extension Version: 2025.2.1.
Platform: linux (x64).
Home = /teamspace/studios/this_studio
Temp Storage folder ~/.vscode-server/data/User/globalStorage/ms-toolsai.jupyter/version-2025.1.0
Workspace folder /teamspace/studios/this_studio
09:45:31.009 [info] Starting Kernel (Python Path: /home/zeus/miniconda3/envs/cloudspace/bin/python, Conda, 3.10.10) for '~/model.ipynb' (disableUI=true)
09:45:32.814 [info] Process Execution: /home/zeus/miniconda3/envs/cloudspace/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:45:32.819 [info] Process Execution: /home/zeus/miniconda3/envs/cloudspace/bin/python -m ipykernel_launcher --f=<username>/.local/share/jupyter/runtime/kernel-v3e005612fbc560f0e43e0e78a5893f4bf852bac0f.json
    > cwd: <username>
09:45:32.829 [info] Process Execution: /home/zeus/miniconda3/envs/cloudspace/bin/python -m pip list
09:45:33.695 [info] Kernel successfully started
09:45:33.735 [info] Process Execution: /home/zeus/miniconda3/envs/cloudspace/bin/python <username>/.vscode-server/extensions/ms-toolsai.jupyter-2025.1.0-linux-x64/pythonFiles/printJupyterDataDir.py
09:49:31.256 [warn] Cell completed with errors [su [Error]: name 'nn' is not defined
	at n.execute (<username>/.vscode-server/extensions/ms-toolsai.jupyter-2025.1.0-linux-x64/dist/extension.node.js:297:4958)] {
  ename: 'NameError',
  evalue: "name 'nn' is not defined",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mNameError\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[1], line 1\x1B[0m\n' +
      '\x1B[0;32m----> 1\x1B[0m \x1B[38;5;28;01mclass\x1B[39;00m\x1B[38;5;250m \x1B[39m\x1B[38;5;21;01mPositionalEncoding\x1B[39;00m(\x1B[43mnn\x1B[49m\x1B[38;5;241m.\x1B[39mModule):\n' +
      '\x1B[1;32m      3\x1B[0m     \x1B[38;5;28;01mdef\x1B[39;00m\x1B[38;5;250m \x1B[39m\x1B[38;5;21m__init__\x1B[39m(\x1B[38;5;28mself\x1B[39m, d_model: \x1B[38;5;28mint\x1B[39m, seq_len: \x1B[38;5;28mint\x1B[39m, dropout: \x1B[38;5;28mfloat\x1B[39m) \x1B[38;5;241m-\x1B[39m\x1B[38;5;241m>\x1B[39m \x1B[38;5;28;01mNone\x1B[39;00m:\n' +
      '\x1B[1;32m      4\x1B[0m         \x1B[38;5;28msuper\x1B[39m()\x1B[38;5;241m.\x1B[39m\x1B[38;5;21m__init__\x1B[39m()\n',
    "\x1B[0;31mNameError\x1B[0m: name 'nn' is not defined"
  ]
}
10:58:06.146 [info] Dispose Kernel '~/model.ipynb' associated with '~/model.ipynb'
10:58:06.167 [warn] Failed to delete connection file file://<username>/.local/share/jupyter/runtime/kernel-v3e005612fbc560f0e43e0e78a5893f4bf852bac0f.json for pid 13242 [Canceled (FileSystemError): Canceled
	at Zi.e (file://<username>/.vscode-server/cli/servers/Stable-e54c774e0add60467559eb0d1e229c6452cf8447/server/out/vs/workbench/api/node/extensionHostProcess.js:112:9922)
	at Object.stat (file://<username>/.vscode-server/cli/servers/Stable-e54c774e0add60467559eb0d1e229c6452cf8447/server/out/vs/workbench/api/node/extensionHostProcess.js:112:7076)
	at async qc.delete (<username>/.vscode-server/extensions/ms-toolsai.jupyter-2025.1.0-linux-x64/dist/extension.node.js:239:15448)
	at async <username>/.vscode-server/extensions/ms-toolsai.jupyter-2025.1.0-linux-x64/dist/extension.node.js:303:469] {
  code: 'Unknown'
}
